name: Docker build
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/labels.yml
      - .github/workflows/security.yml
      - .github/CODEOWNERS
      - .github/CONTRIBUTING.md
      - .github/FUNDING.yml
      - .github/labels.yml
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - README.md
      - title.svg
  push:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/labels.yml
      - .github/workflows/security.yml
      - .github/CODEOWNERS
      - .github/CONTRIBUTING.md
      - .github/FUNDING.yml
      - .github/labels.yml
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - README.md
      - title.svg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build .
